appId: 2

name: Mesa.eth

logoPath: './custom/assets/img/logo.svg'

templatePath: './src/html/index.html'

# Whitelisted tokens from Gnosis Contract retrieved from a smart contract
tcr:
  type: 'multi-tcr' # choices: multi-tcr | none
  config:
    lists:
      - networkId: 1
        listId: 1
        contractAddress: '0x93DB90445B76329e9ed96ECd74e76D8fbf2590d8'

      - networkId: 4
        contractAddress: '0xBb840456546496E7640DC09ba9fE06E67C157E1b'

      - networkId: 100
        listId: 1
        contractAddress: '0x13b47D3311177480E45F223D6f34E1dd5B03b55E'
